services:
  - type: web
    name: raff-khata-backend
    runtime: docker
    dockerfilePath: backend/Dockerfile
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    plan: free
    region: oregon
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "7"
      - key: ALLOWED_ORIGINS
        sync: false
